/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minerva;

import ParentPortal.Home;
import javax.swing.JOptionPane;

/**
 *
 * @author TRETEC
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        yellow = new javax.swing.JLabel();
        black = new javax.swing.JLabel();
        bleu = new javax.swing.JLabel();
        green = new javax.swing.JLabel();
        FamIcon = new javax.swing.JLabel();
        tvm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        incorrect = new javax.swing.JLabel();
        correct = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/Game-29.png"))); // NOI18N
        yellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowMouseClicked(evt);
            }
        });
        jPanel2.add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/Game-28.png"))); // NOI18N
        black.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackMouseClicked(evt);
            }
        });
        jPanel2.add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        bleu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/Game-27.png"))); // NOI18N
        bleu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bleuMouseClicked(evt);
            }
        });
        jPanel2.add(bleu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/Game-26.png"))); // NOI18N
        green.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenMouseClicked(evt);
            }
        });
        jPanel2.add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        FamIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/bgKid-20.png"))); // NOI18N
        jPanel2.add(FamIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 490));

        tvm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/TVM-25.png"))); // NOI18N
        jPanel2.add(tvm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/FamilyIconNoir-19.png"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        incorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/TV-43.png"))); // NOI18N
        jPanel2.add(incorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        correct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minerva/TV-42.png"))); // NOI18N
        jPanel2.add(correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Chewy", 1, 59)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 132, 192));
        jLabel1.setText("IT'S YOUR GAME TIME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Home H = new Home();
        H.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void greenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenMouseClicked
        tvm.setVisible(false);
        correct.setVisible(false);
    }//GEN-LAST:event_greenMouseClicked

    private void blackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackMouseClicked
        tvm.setVisible(false);
        correct.setVisible(false);
    }//GEN-LAST:event_blackMouseClicked

    private void yellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowMouseClicked
                tvm.setVisible(false);
        correct.setVisible(false);
    }//GEN-LAST:event_yellowMouseClicked

    private void bleuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bleuMouseClicked
            tvm.setVisible(false);
        incorrect.setVisible(false);
    }//GEN-LAST:event_bleuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FamIcon;
    private javax.swing.JLabel black;
    private javax.swing.JLabel bleu;
    private javax.swing.JLabel correct;
    private javax.swing.JLabel green;
    private javax.swing.JLabel incorrect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tvm;
    private javax.swing.JLabel yellow;
    // End of variables declaration//GEN-END:variables
}
