/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minerva;

/**
 *
 * @author TRETEC
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setSize(887,697);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Minerva = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        Workload = new javax.swing.JLabel();
        Notices = new javax.swing.JLabel();
        Account = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Achivement = new javax.swing.JLabel();
        Math = new javax.swing.JLabel();
        Geo = new javax.swing.JLabel();
        Tree = new javax.swing.JLabel();
        His = new javax.swing.JLabel();
        Progress = new javax.swing.JLabel();
        PerHome = new javax.swing.JLabel();
        PerSocial = new javax.swing.JLabel();
        perAttendance = new javax.swing.JLabel();
        PerAttention = new javax.swing.JLabel();
        Homework = new javax.swing.JLabel();
        SocialSkills = new javax.swing.JLabel();
        Attendance = new javax.swing.JLabel();
        Attendace = new javax.swing.JLabel();
        Calender = new javax.swing.JLabel();
        CalendarI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(37, 64, 103));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minerva.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Minerva.setForeground(new java.awt.Color(255, 255, 255));
        Minerva.setText("Minerva");
        jPanel2.add(Minerva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("Home");
        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        Contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("Conttact");
        jPanel2.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Workload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Workload.setForeground(new java.awt.Color(255, 255, 255));
        Workload.setText("Workload");
        jPanel2.add(Workload, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        Notices.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Notices.setForeground(new java.awt.Color(255, 255, 255));
        Notices.setText("Notices");
        jPanel2.add(Notices, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Account.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        jPanel2.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(64, 64, 64));
        Welcome.setText("Welcome Mr. Rabah!");
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        Achivement.setBackground(new java.awt.Color(64, 64, 64));
        Achivement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Achivement.setForeground(new java.awt.Color(64, 64, 64));
        Achivement.setText("Achivement");
        jPanel1.add(Achivement, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        Math.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Math-02.png"))); // NOI18N
        jPanel1.add(Math, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        Geo.setForeground(new java.awt.Color(64, 64, 64));
        Geo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Geo-02.png"))); // NOI18N
        jPanel1.add(Geo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        Tree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Tree-02.png"))); // NOI18N
        jPanel1.add(Tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        His.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/His-02.png"))); // NOI18N
        jPanel1.add(His, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        Progress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Progress.setForeground(new java.awt.Color(60, 63, 65));
        Progress.setText("Progress");
        jPanel1.add(Progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        PerHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Per1-02.png"))); // NOI18N
        jPanel1.add(PerHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        PerSocial.setForeground(new java.awt.Color(60, 63, 65));
        PerSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/per2-02.png"))); // NOI18N
        jPanel1.add(PerSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        perAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/per3-02.png"))); // NOI18N
        jPanel1.add(perAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        PerAttention.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/per4-02.png"))); // NOI18N
        jPanel1.add(PerAttention, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        Homework.setForeground(new java.awt.Color(60, 63, 65));
        Homework.setText("HomeWork");
        jPanel1.add(Homework, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        SocialSkills.setForeground(new java.awt.Color(60, 63, 65));
        SocialSkills.setText("Social Skills");
        jPanel1.add(SocialSkills, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        Attendance.setForeground(new java.awt.Color(60, 63, 65));
        Attendance.setText("Attendance");
        jPanel1.add(Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        Attendace.setForeground(new java.awt.Color(60, 63, 65));
        Attendace.setText("Attention");
        jPanel1.add(Attendace, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        Calender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Calender.setForeground(new java.awt.Color(60, 63, 65));
        Calender.setText("Calender");
        jPanel1.add(Calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        CalendarI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Screenshot 2023-01-12 153350.png"))); // NOI18N
        jPanel1.add(CalendarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 480, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JLabel Achivement;
    private javax.swing.JLabel Attendace;
    private javax.swing.JLabel Attendance;
    private javax.swing.JLabel CalendarI;
    private javax.swing.JLabel Calender;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Geo;
    private javax.swing.JLabel His;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Homework;
    private javax.swing.JLabel Math;
    private javax.swing.JLabel Minerva;
    private javax.swing.JLabel Notices;
    private javax.swing.JLabel PerAttention;
    private javax.swing.JLabel PerHome;
    private javax.swing.JLabel PerSocial;
    private javax.swing.JLabel Progress;
    private javax.swing.JLabel SocialSkills;
    private javax.swing.JLabel Tree;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel Workload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel perAttendance;
    // End of variables declaration//GEN-END:variables
}
