/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ParentPortal;

import static ParentPortal.ProgressBarTest.b;
import static ParentPortal.ProgressBarTest.f;
import static ParentPortal.ProgressBarTest.fill;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JProgressBar;
import minerva.KidPortal;

/**
 *
 * @author TRETEC
 */
public class Workload extends javax.swing.JFrame {

    /**
     * Creates new form Workload
     */
    public Workload() {
        initComponents();
    }
    JProgressBar progress;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Achivement = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Achivement1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hibboMenu = new javax.swing.JPanel();
        Minerva = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Workload = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        Account = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Inter Medium", 0, 48)); // NOI18N
        Welcome.setForeground(new java.awt.Color(37, 64, 103));
        Welcome.setText("Workload");
        jPanel14.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 50));

        Achivement.setBackground(new java.awt.Color(64, 64, 64));
        Achivement.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Achivement.setForeground(new java.awt.Color(64, 64, 64));
        Achivement.setText("Ongoing Submissions");
        jPanel14.add(Achivement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/bgCurve-32.png"))); // NOI18N
        jPanel14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 1070, 160));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/extend-19.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 500, 43, 30));

        bg.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 160));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Download-19.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/quizAdd-33.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Achivement1.setBackground(new java.awt.Color(64, 64, 64));
        Achivement1.setFont(new java.awt.Font("Inter Medium", 1, 24)); // NOI18N
        Achivement1.setForeground(new java.awt.Color(37, 64, 103));
        Achivement1.setText("Completed Submissions");
        jPanel3.add(Achivement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 300, 30));

        jPanel4.add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Download-19.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/quizAdd-34.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Upload-23.png"))); // NOI18N
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jPanel4.add(jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Download-19.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/quizAdd-35.png"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel4.add(jPanel8);

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1020, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Counting from 1 to 10");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Writing and Reading numbers");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText(" from 1 to 10 ");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Marks-38.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 170));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Colors");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Choosing colors : 3 Colors");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText(" with near perfect");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Marks-39.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 180, 170));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Colors");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Choosing colors : 3 Colors");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("with near perfect figure");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Marks-40.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 180, 170));

        bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1020, 200));

        jLabel19.setFont(new java.awt.Font("Inter Medium", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(37, 64, 103));
        jLabel19.setText("Homeworks for Fares");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        hibboMenu.setBackground(new java.awt.Color(37, 64, 103));
        hibboMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minerva.setFont(new java.awt.Font("Londrina Solid", 0, 60)); // NOI18N
        Minerva.setForeground(new java.awt.Color(255, 255, 255));
        Minerva.setText("HIBOO");
        hibboMenu.add(Minerva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        hibboMenu.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        Workload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Workload.setForeground(new java.awt.Color(255, 255, 255));
        Workload.setText("Workload");
        hibboMenu.add(Workload, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        Contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("Conttact");
        hibboMenu.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        Account.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
        });
        hibboMenu.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jPanel7.setBackground(new java.awt.Color(37, 64, 103));
        jPanel7.setLayout(new java.awt.GridLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/Design-19.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
        });
        jPanel7.add(jLabel25);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/gear-19-19.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel26);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParentPortal/extend-19.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel27);

        hibboMenu.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 140, 30));

        getContentPane().add(hibboMenu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Home H = new Home();
        H.setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        Account n = new Account();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AccountMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        if(this.getExtendedState () != this.MAXIMIZED_BOTH){
            this.setExtendedState (this.MAXIMIZED_BOTH);
        }else{this.setExtendedState (this.NORMAL);}
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // create a frame
        JFrame f = new JFrame("Downloaded");
 
        // create a panel
        JPanel p = new JPanel();
        JLabel l = new JLabel("Writing Exercise");
        p.add(l);
        // create a progressbar;
        JProgressBar b = new JProgressBar();
 
        // set initial value
        b.setValue(0);
 
        b.setStringPainted(true);
 
        // add progressbar
        p.add(b);
 
        // add panel
        f.add(p);
 
        // set the size of the frame
        f.setSize(270, 100);
        f.setVisible(true);
 
         int i = 0;
            while (i <= 10000) {
                // fill the menu bar
                b.setValue(i + 10);
 
                
                i += 20;
            }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        
// create a frame
        JFrame f = new JFrame("Downloaded");
 
        // create a panel
        JPanel p = new JPanel();
        JLabel l = new JLabel("Choosing Colors");
        p.add(l);
        // create a progressbar
        JProgressBar b = new JProgressBar();
 
        // set initial value
        b.setValue(0);
 
        b.setStringPainted(true);
 
        // add progressbar
        p.add(b);
 
        // add panel
        f.add(p);
 
        // set the size of the frame
        f.setSize(270, 100);
        f.setVisible(true);
 
         int i = 0;
            while (i <= 10000) {
                // fill the menu bar
                b.setValue(i + 10);
 
                
                i += 20;
            }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
// create a frame
        JFrame f = new JFrame("Downloaded");
 
        // create a panel
        JPanel p = new JPanel();
 
        // create a progressbar
        JProgressBar b = new JProgressBar();
        JLabel l = new JLabel("Animals");
        p.add(l);
        // set initial value
        b.setValue(0);
 
        b.setStringPainted(true);
 
        // add progressbar
        p.add(b);
 
        // add panel
        f.add(p);
 
        // set the size of the frame
        f.setSize(270, 100);
        f.setVisible(true);
 
         int i = 0;
            while (i <= 10000) {
                // fill the menu bar
                b.setValue(i + 10);
 
                
                i += 20;
            }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        KidPortal H = new KidPortal();
        H.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked

    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        if(this.getExtendedState () != this.MAXIMIZED_BOTH){
            this.setExtendedState (this.MAXIMIZED_BOTH);
        }else{this.setExtendedState (this.NORMAL);}
    }//GEN-LAST:event_jLabel27MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JLabel Achivement;
    private javax.swing.JLabel Achivement1;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Minerva;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel Workload;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel hibboMenu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
